/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple_crud_interfaces;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import simple_crud.DbConnect;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author dilupa
 */
public class Home extends javax.swing.JFrame {
Connection conn = null;
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        conn = DbConnect.connect();
        loadTable();
    }

    public void loadTable(){
    
            String sql = "SELECT * FROM USERS";
            
            try {
                PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql); 
                ResultSet rst = pst.executeQuery();
            
                user_table.setModel(DbUtils.resultSetToTableModel(rst));
                
        } catch (Exception e) {
                System.out.println(e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        user_table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        user_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        user_role = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbl_id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(820, 644));
        getContentPane().setLayout(null);

        user_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        user_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                user_tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(user_table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(280, 0, 510, 390);

        jLabel1.setText("User name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 150, 60, 14);
        getContentPane().add(user_name);
        user_name.setBounds(100, 140, 110, 30);
        getContentPane().add(user_password);
        user_password.setBounds(100, 190, 110, 30);

        jLabel2.setText("Role");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 250, 60, 14);

        user_role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        getContentPane().add(user_role);
        user_role.setBounds(100, 240, 110, 30);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 60, 14);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 350, 73, 23);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 350, 70, 23);

        lbl_id.setText("ID not found");
        getContentPane().add(lbl_id);
        lbl_id.setBounds(110, 90, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void user_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_user_tableMouseClicked
        // TODO add your handling code here:
      
      int row = user_table.getSelectedRow();
      String id =   user_table.getValueAt(row, 0).toString();
      String name =   user_table.getValueAt(row, 1).toString();
      String password =   user_table.getValueAt(row, 2).toString();
      String role =   user_table.getValueAt(row, 3).toString(); 
      
      
      lbl_id.setText(id);
      user_name.setText(name);
      user_password.setText(password);
      user_role.setSelectedItem(role);
        
    }//GEN-LAST:event_user_tableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int id = Integer.parseInt(lbl_id.getText());
        
        String sql = "DELETE FROM USERS WHERE ID = ?";
        
        try {
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);   
            pst.setInt(1, id);
            boolean execute = pst.execute();
            
        if(execute){
            JOptionPane.showMessageDialog(null,"Error","Error",JOptionPane.ERROR_MESSAGE);  
        }else{
            JOptionPane.showMessageDialog(null, "Successfully deleted");
        }
             
            
        } catch (Exception e) {
        }
        loadTable();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    int id = Integer.parseInt(lbl_id.getText());    
     
    String userName = user_name.getText();
    String userPassword = user_password.getText();
    String userRole = user_role.getSelectedItem().toString();
        
        String sql = "UPDATE USERS SET USER_NAME = ?, PASSWORD = ?, ROLE = ? WHERE ID = ?";
        
        try {
        PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);   
            pst.setString(1, userName);
            pst.setString(2, userPassword);
            pst.setString(3, userRole);    
            pst.setInt(4, id);   
            
            pst.execute();
        } catch (Exception e) {
            System.out.println(e);
        }
        
        loadTable();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JTextField user_name;
    private javax.swing.JTextField user_password;
    private javax.swing.JComboBox<String> user_role;
    private javax.swing.JTable user_table;
    // End of variables declaration//GEN-END:variables
}
