/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple_crud_interfaces;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import javax.swing.JOptionPane;
import simple_crud.DbConnect;

/**
 *
 * @author dilupa
 */
public class Register extends javax.swing.JFrame {
    Connection conn = null;
    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        conn = DbConnect.connect();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        user_name = new javax.swing.JTextField();
        confirm_password = new javax.swing.JTextField();
        password = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        role = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 444));
        getContentPane().setLayout(null);

        jLabel1.setText("ConfirmPassword");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 210, 100, 14);
        getContentPane().add(user_name);
        user_name.setBounds(190, 120, 130, 30);
        getContentPane().add(confirm_password);
        confirm_password.setBounds(190, 210, 130, 30);
        getContentPane().add(password);
        password.setBounds(190, 160, 130, 30);

        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 160, 60, 14);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Register");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(290, 20, 150, 50);

        jButton1.setText("Back to login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(190, 350, 100, 30);

        jButton2.setText("Register Me");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 350, 100, 30);

        jLabel5.setText("Role");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 130, 70, 14);

        role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "User", "Admin" }));
        getContentPane().add(role);
        role.setBounds(510, 120, 90, 30);

        jLabel6.setText("User name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(70, 120, 70, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Login pageLogin = new Login();
        pageLogin.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    String userName = user_name.getText();
    String userPassword = password.getText();
    String userConfirmPassword = confirm_password.getText();
    String userRole = role.getSelectedItem().toString();
    
    if(userConfirmPassword.equals(userPassword)){
    String sql = "INSERT INTO USERS(USER_NAME,PASSWORD,ROLE) VALUES(?,?,?)";

        try {
            PreparedStatement pst = (PreparedStatement) conn.prepareStatement(sql);   
            pst.setString(1, userName);
            pst.setString(2, userPassword);
            pst.setString(3, userRole);
            
        boolean execute = pst.execute();
        
        if(execute){
        JOptionPane.showMessageDialog(null,"Error","Error",JOptionPane.ERROR_MESSAGE);  
        }else{
        JOptionPane.showMessageDialog(null, "Successfully added");
        }
        
            
        } catch (Exception e) {
            System.out.print(e);
        }
    }else{
    JOptionPane.showMessageDialog(null,"Passwords not matched!","Error",JOptionPane.ERROR_MESSAGE);  
    }
    
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField confirm_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField password;
    private javax.swing.JComboBox<String> role;
    private javax.swing.JTextField user_name;
    // End of variables declaration//GEN-END:variables
}
